% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Feb-2020 10:32:09
%  MATLAB version: 9.7.0.1296695 (R2019b) Update 4
% -------------------------------------------------------------------
                                 

Variant = Simulink.Variant;
Variant.Condition = 'Variant1 == 1';

Variant1 = Simulink.Parameter;
Variant1.Value = 1;
Variant1.CoderInfo.StorageClass = 'Custom';
Variant1.CoderInfo.Alias = '';
Variant1.CoderInfo.Alignment = -1;
Variant1.CoderInfo.CustomStorageClass = 'CompilerFlag';
Variant1.Description = '';
Variant1.DataType = 'uint8';
Variant1.Min = [];
Variant1.Max = [];
Variant1.DocUnits = '';

Variant2 = Simulink.Parameter;
Variant2.Value = 2;
Variant2.CoderInfo.StorageClass = 'Custom';
Variant2.CoderInfo.Alias = '';
Variant2.CoderInfo.Alignment = -1;
Variant2.CoderInfo.CustomStorageClass = 'CompilerFlag';
Variant2.Description = '';
Variant2.DataType = 'uint8';
Variant2.Min = [];
Variant2.Max = [];
Variant2.DocUnits = '';

VariantSub = Simulink.Variant;
VariantSub.Condition = 'Variant2 == 1';

VariantSub2 = Simulink.Variant;
VariantSub2.Condition = 'Variant2 == 2';

